/*
 * version.h
 *
 *  Created on: Dec 9, 2020
 *      Author: dkoes
 */

#ifndef SRC_LIB_VERSION_H_
#define SRC_LIB_VERSION_H_

// These variables are autogenerated into version.cpp and compiled
// into the library by the version.cmake script

extern const char* GIT_TAG;
extern const char* GIT_REV;
extern const char* GIT_BRANCH;


#endif /* SRC_LIB_VERSION_H_ */
